name: figgocabs
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0
  google_sign_in: ^6.0.2
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  location: ^4.2.0
  path_provider: ^2.0.15
  url_launcher: ^6.1.10
  flutter_polyline_points: ^1.0.0
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  sliding_clipped_nav_bar: ^3.1.0+4
  flutter_google_places: ^0.3.0
  sms_autofill: ^2.3.0
  get: ^4.6.5
  avatar_glow: ^2.0.2
  lottie: ^2.3.2
  nb_utils: ^5.0.8
  cached_network_image: ^3.2.3
  loading_animation_widget: ^1.2.0+4
  connectivity_plus: ^3.0.2
  image_picker: ^0.8.5+3
  file_picker: ^5.2.0+1
  liquid_swipe: ^3.1.0
  cool_alert: ^2.0.1
  top_snackbar_flutter: ^3.0.0+1
  get_storage: ^2.1.1
  shimmer: ^2.0.0
  page_transition: ^2.0.9
  animated_digit: ^3.2.1
  firebase_messaging: ^14.4.1
  sliding_up_panel: ^2.0.0+1
  flutter_svg: ^2.0.5
  flutter_stripe: ^5.0.0
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^14.0.0+1
  swipeable_card_stack: ^0.0.5
  fbroadcast: ^2.0.0
  dotted_line: ^3.1.0
  razorpay_flutter: ^1.3.0
  rating_dialog: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/images/corosal/
    - assets/images/bottomMenu/
    - assets/.env
    - assets/map_style.txt

